import { describe, expect, it, vi } from 'vitest'
import type { MarketplaceEntry, SearchMarketplaceValue, SkillDraft, SkillManagerInventory } from '@deepseek-ai/dsh-api-remotes/client'
import { SkillsController, type RemoteResult, type SkillManagerRemote } from '../src/client/controller.ts'
import { entry, inventory, source } from './fixtures.client.ts'

const ok = <T>(value: T): RemoteResult<T> => ({ ok: true, value })
const fail = (message: string): RemoteResult<never> => ({ ok: false, error: { code: 'skill-manager/invalid-request', message } })

type MockRemote = SkillManagerRemote & Record<keyof SkillManagerRemote, ReturnType<typeof vi.fn>>

function remote(overrides: Partial<SkillManagerRemote> = {}): MockRemote {
  return {
    inventory: vi.fn(async () => ok(inventory())),
    setEnabled: vi.fn(async () => ok(undefined)),
    clearOverride: vi.fn(async () => ok(undefined)),
    sources: vi.fn(async () => ok({ sources: [source()] })),
    addSource: vi.fn(async () => ok({ source: source({ id: 'extra', origin: 'user', syncState: 'syncing' }) })),
    syncSource: vi.fn(async () => ok({ source: source() })),
    setSourceEnabled: vi.fn(async () => ok({ source: source() })),
    removeSource: vi.fn(async () => ok(undefined)),
    readSkill: vi.fn(async ({ name }: { name: string }) => ok({ skill: { name, description: 'Stored', whenToUse: 'Often', body: 'Body', modelInvocable: true, userInvocable: false }, path: `/home/.dsh/skills/${name}/SKILL.md`, editable: true })),
    createSkill: vi.fn(async (skill: SkillDraft) => ok({ skill, path: '/p' })),
    updateSkill: vi.fn(async (skill: SkillDraft) => ok({ skill, path: '/p' })),
    deleteSkill: vi.fn(async () => ok(undefined)),
    customizeSkill: vi.fn(async ({ name }: { name: string }) => ok({ skill: { name, description: 'Copy', body: 'Copied', modelInvocable: true, userInvocable: true }, path: `/home/.dsh/skills/${name}/SKILL.md`, editable: true })),
    uninstallSkill: vi.fn(async () => ok(undefined)),
    marketplaces: vi.fn(async () => ok({ marketplaces: [{ id: 'anthropic', title: 'Anthropic', kind: 'github' as const, url: 'https://github.com/anthropics/skills', enabled: true, browsable: true, available: 20 }], available: true })),
    searchMarketplace: vi.fn(async () => ok(page([entry('pdf'), entry('docx')], true))),
    installSkill: vi.fn(async () => ok({ source: source() })),
    checkUpdates: vi.fn(async () => ok({ sources: [source({ updateAvailable: true })] })),
    ...overrides,
  } as never
}

function page(skills: MarketplaceEntry[], hasMore = false, nextOffset = 24): SearchMarketplaceValue {
  return { skills, totals: { anthropic: skills.length }, hasMore, nextOffset, errors: [] }
}

async function settle(): Promise<void> {
  for (let index = 0; index < 5; index += 1) await Promise.resolve()
}

describe('SkillsController', () => {
  it('loads both views once and reloads on refresh', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    const face = controller.inject()
    expect(controller.state().status).toBe('idle')
    face.ensure()
    expect(controller.state()).toMatchObject({ status: 'loading', sourcesStatus: 'loading' })
    await settle()
    expect(controller.state()).toMatchObject({ status: 'ready', sourcesStatus: 'ready', sources: [{ id: 'anthropic-skills' }] })
    face.ensure()
    expect(api.inventory).toHaveBeenCalledTimes(1)
    face.refresh()
    await settle()
    expect(api.inventory).toHaveBeenCalledTimes(2)
    expect(face.hooks.skills).toBe(controller.store)
  })

  it('reports load failures as page errors first and as notices after a successful load', async () => {
    const api = remote({ inventory: vi.fn(async () => fail('host down')), sources: vi.fn(async () => fail('no sources')) })
    const controller = new SkillsController(api)
    await controller.load()
    expect(controller.state()).toMatchObject({ status: 'error', error: 'host down', sourcesStatus: 'error', sourcesError: 'no sources' })
    api.inventory.mockResolvedValueOnce(ok(inventory()))
    api.sources.mockResolvedValueOnce(ok({ sources: [] }))
    await controller.load()
    expect(controller.state()).toMatchObject({ status: 'ready', sourcesStatus: 'ready' })
    expect(controller.state().error).toBeUndefined()
    api.inventory.mockResolvedValueOnce(fail('flaky'))
    await controller.load()
    expect(controller.state()).toMatchObject({ status: 'ready', notice: 'flaky' })
    controller.inject().dismissNotice()
    expect(controller.state().notice).toBeUndefined()
  })

  it('toggles optimistically, then settles on the Host result or rolls back', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.toggleSkill('alpha', false)
    expect(controller.state().inventory?.skills[0]).toMatchObject({ enabled: false, preference: 'global' })
    expect(controller.state().pendingSkills).toEqual(['alpha'])
    await settle()
    expect(api.setEnabled).toHaveBeenCalledWith({ name: 'alpha', enabled: false })
    expect(controller.state().pendingSkills).toEqual([])

    api.setEnabled.mockResolvedValueOnce(fail('disk full'))
    face.toggleSkill('beta', true)
    await settle()
    expect(controller.state().inventory?.skills[1]).toMatchObject({ enabled: false, preference: 'global' })
    expect(controller.state().notice).toBe('disk full')
  })

  it('writes project overrides in a project scope, resets them, and drops a vanished project', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.resetSkill('alpha')
    expect(api.clearOverride).not.toHaveBeenCalled()

    face.selectProject('/work/app')
    await settle()
    expect(api.inventory).toHaveBeenLastCalledWith({ projectRoot: '/work/app' })
    face.toggleSkill('alpha', false)
    await settle()
    expect(api.setEnabled).toHaveBeenCalledWith({ name: 'alpha', enabled: false, projectRoot: '/work/app' })
    face.resetSkill('alpha')
    await settle()
    expect(api.clearOverride).toHaveBeenCalledWith({ name: 'alpha', projectRoot: '/work/app' })

    api.inventory.mockResolvedValue(ok(inventory({ projects: [] })))
    face.selectProject('/gone')
    await settle()
    expect(controller.state().projectRoot).toBeUndefined()
  })

  it('ignores a stale inventory response and responses after disposal', async () => {
    let release: (value: RemoteResult<SkillManagerInventory>) => void = () => {}
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    api.inventory.mockReturnValueOnce(new Promise<RemoteResult<SkillManagerInventory>>((resolve) => { release = resolve }))
    const face = controller.inject()
    face.selectProject('/work/app')
    face.selectProject(undefined)
    await settle()
    release(ok(inventory({ skills: [] })))
    await settle()
    expect(controller.state().inventory?.skills).toHaveLength(2)

    controller.dispose()
    api.inventory.mockResolvedValueOnce(ok(inventory({ skills: [] })))
    await controller.load()
    face.toggleSkill('alpha', false)
    face.syncSource('anthropic-skills')
    face.openAdd()
    face.editAdd({ url: 'github:o/r' })
    face.submitAdd()
    await settle()
    expect(controller.state().inventory?.skills).toHaveLength(2)
    expect(controller.state().add.busy).toBe(true)
  })

  it('adds a source through the dialog draft and keeps the draft on failure', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.openAdd()
    face.submitAdd()
    expect(api.addSource).not.toHaveBeenCalled()
    face.editAdd({ url: ' github:o/r ', ref: ' main ', path: ' ' })
    api.addSource.mockResolvedValueOnce(fail('unsupported'))
    face.submitAdd()
    expect(controller.state().add.busy).toBe(true)
    face.closeAdd()
    expect(controller.state().add.open).toBe(true)
    face.submitAdd()
    await settle()
    expect(api.addSource).toHaveBeenCalledTimes(1)
    expect(api.addSource).toHaveBeenCalledWith({ url: 'github:o/r', ref: 'main' })
    expect(controller.state().add).toMatchObject({ open: true, busy: false, error: 'unsupported' })
    face.editAdd({ path: 'skills' })
    expect(controller.state().add.error).toBeUndefined()
    face.submitAdd()
    await settle()
    expect(api.addSource).toHaveBeenLastCalledWith({ url: 'github:o/r', ref: 'main', path: 'skills' })
    expect(controller.state().add.open).toBe(false)
    face.openAdd()
    face.closeAdd()
    expect(controller.state().add.open).toBe(false)
  })

  it('runs source operations, reflects the switch immediately, and reports failures', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.toggleSource('anthropic-skills', false)
    expect(controller.state().sources[0]?.enabled).toBe(false)
    expect(controller.state().pendingSources).toEqual(['anthropic-skills'])
    await settle()
    expect(api.setSourceEnabled).toHaveBeenCalledWith({ id: 'anthropic-skills', enabled: false })
    expect(controller.state().pendingSources).toEqual([])
    face.syncSource('anthropic-skills')
    await settle()
    expect(api.syncSource).toHaveBeenCalledWith({ id: 'anthropic-skills' })
    api.removeSource.mockResolvedValueOnce(fail('locked'))
    face.removeSource('anthropic-skills')
    await settle()
    expect(controller.state().notice).toBe('locked')
    controller.inject().toggleSource('unknown', true)
    expect(controller.state().sources.map(entry => entry.id)).toEqual(['anthropic-skills'])
  })

  it('reports a failed override reset without changing the row', async () => {
    const api = remote({ clearOverride: vi.fn(async () => fail('not allowed')) })
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.selectProject('/work/app')
    await settle()
    face.resetSkill('alpha')
    await settle()
    expect(controller.state().notice).toBe('not allowed')
    expect(controller.state().inventory?.skills[0]).toMatchObject({ enabled: true, preference: 'default' })
  })

  it('leaves the snapshot unchanged when toggling before the inventory loads', () => {
    const controller = new SkillsController(remote())
    controller.inject().toggleSkill('alpha', true)
    expect(controller.state().inventory).toBeUndefined()
  })

  it('creates a skill from a trimmed draft and reloads the inventory', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.openCreate()
    expect(controller.state().editor).toMatchObject({ open: true, mode: 'create' })
    face.editDraft({ name: ' notes ', description: ' Take notes ', whenToUse: '   ', body: 'Body' })
    face.saveEditor()
    expect(controller.state().editor.busy).toBe(true)
    face.saveEditor()
    face.closeEditor()
    expect(controller.state().editor.open).toBe(true)
    await settle()
    expect(api.createSkill).toHaveBeenCalledTimes(1)
    expect(api.createSkill).toHaveBeenCalledWith({ name: 'notes', description: 'Take notes', body: 'Body', modelInvocable: true, userInvocable: true })
    expect(controller.state().editor.open).toBe(false)
    expect(api.inventory).toHaveBeenCalledTimes(2)
    face.openCreate()
    face.closeEditor()
    expect(controller.state().editor.open).toBe(false)
  })

  it('loads a skill for editing, keeps the dialog on failure, and saves with when-to-use', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.openEdit('alpha')
    expect(controller.state().editor).toMatchObject({ open: true, mode: 'edit', loading: true })
    face.saveEditor()
    expect(api.updateSkill).not.toHaveBeenCalled()
    await settle()
    expect(controller.state().editor).toMatchObject({ loading: false, draft: { name: 'alpha', description: 'Stored', whenToUse: 'Often' } })
    api.updateSkill.mockResolvedValueOnce(fail('disk full'))
    face.saveEditor()
    await settle()
    expect(controller.state().editor).toMatchObject({ open: true, busy: false, error: 'disk full' })
    face.editDraft({ body: 'New' })
    expect(controller.state().editor.error).toBeUndefined()
    face.saveEditor()
    await settle()
    expect(api.updateSkill).toHaveBeenLastCalledWith({ name: 'alpha', description: 'Stored', whenToUse: 'Often', body: 'New', modelInvocable: true, userInvocable: false })
    expect(controller.state().editor.open).toBe(false)
  })

  it('reports read failures in the editor and ignores a read the user abandoned', async () => {
    const api = remote({ readSkill: vi.fn(async () => fail('not yours')) })
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.openEdit('beta')
    await settle()
    expect(controller.state().editor).toMatchObject({ loading: false, error: 'not yours' })
    face.openEdit('alpha')
    face.openCreate()
    await settle()
    expect(controller.state().editor).toMatchObject({ mode: 'create', draft: { name: '' } })
  })

  it('deletes a skill, marks it pending, and reports failures', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.deleteSkill('alpha')
    expect(controller.state().pendingSkills).toEqual(['alpha'])
    await settle()
    expect(api.deleteSkill).toHaveBeenCalledWith({ name: 'alpha' })
    expect(controller.state().pendingSkills).toEqual([])
    api.deleteSkill.mockResolvedValueOnce(fail('read-only'))
    face.deleteSkill('beta')
    await settle()
    expect(controller.state().notice).toBe('read-only')
  })

  it('ignores editor responses after disposal', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    controller.dispose()
    face.openEdit('alpha')
    face.deleteSkill('alpha')
    await settle()
    expect(controller.state().editor.loading).toBe(true)
    expect(controller.state().pendingSkills).toEqual(['alpha'])
    face.openCreate()
    face.editDraft({ name: 'x', description: 'y' })
    face.saveEditor()
    await settle()
    expect(controller.state().editor.busy).toBe(true)
  })

  it('checks for updates after the first load and syncs every source with an update', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    const face = controller.inject()
    face.ensure()
    await settle()
    await settle()
    expect(api.checkUpdates).toHaveBeenCalledTimes(1)
    expect(controller.state()).toMatchObject({ checking: false, sources: [{ updateAvailable: true }] })
    face.updateAll()
    await settle()
    expect(api.syncSource).toHaveBeenCalledWith({ id: 'anthropic-skills' })
    api.checkUpdates.mockResolvedValueOnce(fail('rate limited'))
    face.checkUpdates()
    face.checkUpdates()
    await settle()
    expect(api.checkUpdates).toHaveBeenCalledTimes(2)
    expect(controller.state().notice).toBe('rate limited')
    controller.dispose()
    face.checkUpdates()
    await settle()
    expect(controller.state().checking).toBe(true)
  })

  it('customizes a skill into the editor and uninstalls remote skills', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    await controller.load()
    const face = controller.inject()
    face.customizeSkill('beta')
    expect(controller.state().pendingSkills).toEqual(['beta'])
    await settle()
    expect(controller.state().editor).toMatchObject({ open: true, mode: 'edit', draft: { name: 'beta', body: 'Copied' } })
    api.customizeSkill.mockResolvedValueOnce(fail('exists'))
    face.customizeSkill('beta')
    await settle()
    expect(controller.state().notice).toBe('exists')

    face.inspect('beta')
    await settle()
    face.uninstallSkill('beta')
    await settle()
    expect(api.uninstallSkill).toHaveBeenCalledWith({ name: 'beta' })
    expect(controller.state().inspected).toBeUndefined()
    face.inspect('alpha')
    await settle()
    face.uninstallSkill('beta')
    await settle()
    expect(controller.state().inspected?.name).toBe('alpha')
    api.uninstallSkill.mockResolvedValueOnce(fail('not remote'))
    face.uninstallSkill('alpha')
    await settle()
    expect(controller.state().notice).toBe('not remote')
    controller.dispose()
    face.customizeSkill('x')
    face.uninstallSkill('x')
    await settle()
    expect(controller.state().pendingSkills).toEqual(['x', 'x'])
  })

  it('loads marketplaces once, searches, pages, and filters by marketplace', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    const face = controller.inject()
    face.ensureDiscover()
    expect(controller.state().discover.status).toBe('loading')
    await settle()
    await settle()
    face.ensureDiscover()
    expect(api.marketplaces).toHaveBeenCalledTimes(1)
    expect(api.marketplaces).toHaveBeenCalledWith({ refresh: true })
    expect(controller.state().discover).toMatchObject({ status: 'ready', available: true, hasMore: true, offset: 24, results: [{ key: 'o/r/pdf' }, { key: 'o/r/docx' }] })
    expect(api.searchMarketplace).toHaveBeenLastCalledWith({ query: '', offset: 0 })

    api.searchMarketplace.mockResolvedValueOnce(ok(page([entry('docx'), entry('xlsx')], false, 48)))
    face.loadMore()
    face.loadMore()
    await settle()
    expect(api.searchMarketplace).toHaveBeenLastCalledWith({ query: '', offset: 24 })
    expect(controller.state().discover.results.map(item => item.name)).toEqual(['pdf', 'docx', 'xlsx'])
    face.loadMore()
    expect(api.searchMarketplace).toHaveBeenCalledTimes(2)

    face.selectMarketplace('anthropic')
    face.search('  pdf ')
    expect(controller.state().discover.searching).toBe(true)
    await settle()
    expect(api.searchMarketplace).toHaveBeenLastCalledWith({ query: 'pdf', marketplace: 'anthropic', offset: 0 })
    expect(controller.state().discover).toMatchObject({ query: '  pdf ', searching: false })

    api.searchMarketplace.mockResolvedValueOnce(fail('down'))
    face.search('x')
    await settle()
    expect(controller.state().discover.errors).toEqual([{ marketplace: 'anthropic', message: 'down' }])
    face.selectMarketplace(undefined)
    api.searchMarketplace.mockResolvedValueOnce(fail('down'))
    face.search('y')
    await settle()
    expect(controller.state().discover.errors).toEqual([{ marketplace: '', message: 'down' }])
  })

  it('drops a superseded search, reports marketplace failures, and stops when the service is missing', async () => {
    let release: (value: RemoteResult<SearchMarketplaceValue>) => void = () => {}
    const api = remote()
    const controller = new SkillsController(api)
    const face = controller.inject()
    face.ensureDiscover()
    await settle()
    await settle()
    api.searchMarketplace.mockReturnValueOnce(new Promise((resolve) => { release = resolve }))
    face.search('slow')
    face.search('fast')
    await settle()
    release(ok(page([entry('stale')])))
    await settle()
    expect(controller.state().discover.results.map(item => item.name)).toEqual(['pdf', 'docx'])

    const failing = new SkillsController(remote({ marketplaces: vi.fn(async () => fail('offline')) }))
    failing.inject().ensureDiscover()
    await settle()
    expect(failing.state().discover).toMatchObject({ status: 'error', error: 'offline' })

    const missing = remote({ marketplaces: vi.fn(async () => ok({ marketplaces: [], available: false })) })
    const unmounted = new SkillsController(missing)
    unmounted.inject().ensureDiscover()
    await settle()
    expect(unmounted.state().discover).toMatchObject({ status: 'ready', available: false })
    expect(missing.searchMarketplace).not.toHaveBeenCalled()

    const disposed = new SkillsController(remote())
    disposed.inject().ensureDiscover()
    disposed.dispose()
    await settle()
    expect(disposed.state().discover.status).toBe('loading')
    const late = new SkillsController(remote())
    late.inject().search('x')
    late.dispose()
    await settle()
    expect(late.state().discover.searching).toBe(true)
  })

  it('installs an entry once, shows it installing until synced, and restores it on failure', async () => {
    const api = remote()
    const controller = new SkillsController(api)
    const face = controller.inject()
    face.ensureDiscover()
    await settle()
    await settle()
    const [pdf, docx] = controller.state().discover.results as [MarketplaceEntry, MarketplaceEntry]
    face.install(pdf)
    face.install(pdf)
    expect(controller.state().discover.installing).toEqual(['o/r/pdf'])
    expect(controller.state().discover.results[0]?.state).toBe('installing')
    await settle()
    expect(api.installSkill).toHaveBeenCalledTimes(1)
    expect(api.installSkill).toHaveBeenCalledWith({ repository: 'o/r', name: 'pdf', dir: 'skills/pdf' })
    expect(controller.state().discover.results[0]?.state).toBe('installed')

    api.installSkill.mockResolvedValueOnce(ok({ source: source({ syncState: 'syncing' }) }))
    face.install({ ...docx, dir: undefined } as never)
    await settle()
    expect(api.installSkill).toHaveBeenLastCalledWith({ repository: 'o/r', name: 'docx' })
    expect(controller.state().discover.results[1]?.state).toBe('installing')

    api.installSkill.mockResolvedValueOnce(fail('no network'))
    face.install(docx)
    await settle()
    expect(controller.state().discover.results[1]?.state).toBe('available')
    expect(controller.state().notice).toBe('no network')
    controller.dispose()
    face.install(pdf)
    await settle()
    expect(controller.state().discover.installing).toEqual(['o/r/pdf'])
  })
})
